### ISSUE TITLE
bug - grasshopperunloadplugin

### ISSUE THREAD

**Issue by johnharding** [johnharding/Biomorpher#12]
You will get a crash with any examples using biomorpher **and genepools**, if you use grasshopper unload plugin and then load grasshopper again. I don't know why!!

**Comment by pearswj** [comment]
The `GrasshopperUnloadPlugin` command is being removed in Rhino 6/Grasshopper 1.0 because it doesn't really do what it's supposed to do. You can't actually unload a .NET assembly that has been loaded (unless you do some jiggery pokery with multiple AppDomains).

**Comment by johnharding** [comment]
Thanks for letting us know @pearswj . One less thing to resolve!
